export const constants = {
  MYSQL_SERVER: 'MYSQL_SERVER',
  MYSQL_PORT: 'MYSQL_PORT',
  MYSQL_USER: 'MYSQL_USER',
  MYSQL_PASSWORD: 'MYSQL_PASSWORD',
  MYSQL_DATABASE: 'MYSQL_DATABASE',
  MYSQL_SCHEMA: 'MYSQL_SCHEMA',
  PORT: 'PORT',
  NODE_ENV: 'development',
  JWT_SECRET: 'JWT_SECRET',
}
