export const constants = {
  JWT_SECRET: 'JWT_SECRET',
  JWT_REFRESH: 'JWT_REFRESH',
  MYSQL_SERVER: 'MYSQL_SERVER',
  MYSQL_PORT: 'MYSQL_PORT',
  MYSQL_USER: 'MYSQL_USER',
  MYSQL_PASSWORD: 'MYSQL_PASSWORD',
  MYSQL_DATABASE: 'MYSQL_DATABASE',
  MYSQL_SCHEMA: 'MYSQL_SCHEMA',
  MYSQL_TRUST_SERVER_CERTIFICATE: 'MYSQL_TRUST_SERVER_CERTIFICATE',
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
}
